project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

# Do not set "update_option"
# Always invalid transilation when source string changes
files:
  - source: 'app.json'
    translation: '/translation/%locale_with_underscore%/%original_file_name%'
  - source: 'app.stringsdict'
    translation: '/translation/%locale_with_underscore%/%original_file_name%'
  - source: 'ios-infoPlist.json'
    translation: '/translation/%locale_with_underscore%/%original_file_name%'
